### ISSUE TITLE
No vendor/autoload.php

### ISSUE THREAD

**Issue by bitflop** [fansoro/fansoro#64]
I was just looking at the code in index.php where the autoloader is being loaded. There is no "autoload.php" file in the repo.

```
require_once __DIR__ . '/vendor/autoload.php';
```

**Comment by Awilum** [comment]
because you need to 
1. Download Composer
2. run with console in project folder: php composer.phar install

**Comment by Awilum** [comment]
But in release build you will find `vendor` folder https://github.com/morfy-cms/morfy/releases/tag/v2.0.0

**Comment by Razzwan** [comment]
yes, but if you install with composer all files was added.

2015-11-20 21:50 GMT+02:00 KNL <notifications@github.com>:

**Comment by Awilum** [comment]
@Razzwan okey, I will recheck this.

**Comment by Awilum** [comment]
@bitflop @Razzwan 

Working examples

1. 
```
php composer.phar create-project morfy-cms/morfy
```
2.
```
composer create-project morfy-cms/morfy
```
