### ISSUE TITLE
Warning: Blocks.php on line 43

### ISSUE THREAD

**Issue by pafnuty** [fansoro/fansoro#70]
Как понимаю проблема из-за ситуации, когда нет блоков

Warning: Invalid argument supplied for foreach() in W:\domains\morfy.org\morfy\Blocks.php on line 43
```
$blocks = File::scan(STORAGE_PATH . '/blocks', 'md');

        foreach ($blocks as $block) {
            $blocks_cache_id .= filemtime($block);
        }
```

**Comment by Awilum** [comment]
Fixed in 2.0.3
