### ISSUE TITLE
I cannot view the link index, contact, etc., It seems something wrong in htaccess file?

### ISSUE THREAD

**Issue by dangminhtuan** [fansoro/fansoro#71]
![morfy1](https://cloud.githubusercontent.com/assets/16283565/12069753/2632aade-b07c-11e5-9f75-e7669cfba1bd.png)

**Comment by Awilum** [comment]
rewrite base in htaccess

**Comment by ebookcode** [comment]
I met the same problem, how to fix the htaccess file? or to check htaccess mode enable or not?

**Comment by tovic** [comment]
~~~ .htaccess
RewriteBase /cms/flatfile-cms/morfy-2.0.2
~~~

**Comment by ebookcode** [comment]
thank @tovic  it works

**Comment by mapadesign** [comment]
@dangminhtuan Mark as solved, and close issue.
Thanks
